# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
