# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20170711_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_required',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Required'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
    ]
